name: "Build and push docker image"
on:
  pull_request:
    types: [opened, synchronize, reopened]

  push:
    branches:
      - '*'

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - uses: actions/checkout@v2.3.1
    - uses: cachix/install-nix-action@v11
      with:
        nix_path: nixpkgs=channel:nixos-19.09
    - uses: cachix/cachix-action@v6
      with:
        name: deni
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        # Only needed for private caches
        #authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: echo "::set-env name=SHORT_SHA::$(git rev-parse --short HEAD)"
    - name: Build docker image with Nix
      run: nix-build --attr backend-docker-image release.nix
    - name: Load docker image
      run: docker load < ./result
    - name: Tag docker image with SHORT SHA
      run: docker tag $GITHUB_REPOSITORY:latest $GITHUB_REPOSITORY:$SHORT_SHA
      if: ${GITHUB_REF} == 'refs/heads/master'
    - name: Login to DockerHub
      uses: docker/login-action@v1
      if: ${GITHUB_REF} == 'refs/heads/master'
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push docker image tagged as latest
      run: docker push $GITHUB_REPOSITORY:latest
      if: ${GITHUB_REF} == 'refs/heads/master'
    - name: Push docker image tagged with SHORT_SHA
      run: docker push $GITHUB_REPOSITORY:$SHORT_SHA
      if: ${GITHUB_REF} == 'refs/heads/master'
