name: "Build and push docker image"
on:
  pull_request:
  push:
jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}    - uses: actions/checkout@v2.3.1
    - uses: cachix/install-nix-action@v11
      with:
        nix_path: nixpkgs=channel:nixos-19.09
    - uses: cachix/cachix-action@v6
      with:
        name: deni
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        # Only needed for private caches
        #authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-build --attr backend-docker-image release.nix
    - run: nix-shell --run "echo OK"
    - run: docker load < ./result
    - run: docker push denibertovic/nuts-and-bolts:latest
